image: 0xacab.org:4567/riseuplabs/docker/crabgrass:latest

services:
  - mysql:5.5

variables:
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  MYSQL_HOST: 'mysql'

cache:
  key: shared
  paths:
    - vendor/ruby

before_script:
  - ruby -v
  - which ruby
  - bundle install -j $(nproc) --path vendor "${FLAGS[@]}"

bundle_audit:
  stage: test
  allow_failure: true
  script: |
    sudo gem install bundler-audit
    bundle-audit update
    bundle-audit check

test:
  stage: test
  script: |
    bundle exec rake create_a_secret
    cp config/database.yml.example config/database.yml
    bundle exec rake db:create
    bundle exec rake db:schema:load
    bundle exec rake cg:test:update_fixtures
    bundle exec rake db:test:prepare
    RAILS_ENV=test bundle exec rake db:fixtures:load
    RAILS_ENV=test bundle exec rake ts:index ts:start
    bundle exec rake
    bundle exec rake cg:cleanup:all     # test cleanup tasks
  artifacts:
    when: on_failure
    paths:
      - log/test.log
      - tmp/*.log
      - tmp/*.html
      - tmp/*.png

test_stretch:
  image: 0xacab.org:4567/riseuplabs/docker/crabgrass:stretch_amd64
  stage: test
  script: |
    bundle exec rake create_a_secret
    cp config/database.yml.example config/database.yml
    bundle exec rake db:create
    bundle exec rake db:schema:load
    bundle exec rake cg:test:update_fixtures
    bundle exec rake db:test:prepare
    RAILS_ENV=test bundle exec rake db:fixtures:load
    RAILS_ENV=test bundle exec rake ts:index ts:start
    bundle exec rake
    bundle exec rake cg:cleanup:all     # test cleanup tasks
  artifacts:
    when: on_failure
    paths:
      - log/test.log
      - tmp/*.log
      - tmp/*.html
      - tmp/*.png
