language: ruby
# only install ci and assets gems:
bundler_args: --without production:development:test
env:
  - RAKE_TASK=test
  - RAKE_TASK=test:pages:all
rvm:
  - 1.9.3
#  - 2.0.0
matrix:
  fast_finish: true
#  allow_failures:
#    - rvm: 2.0.0
before_install:
  - "bundle --version"
  - sudo apt-get update
  - sudo apt-get install -y graphicsmagick
  - sudo apt-get install -y libreoffice-common
  - sudo apt-get install -y sphinxsearch
  - sudo apt-get install -y inkscape
before_script:
  - "bundle exec rake create_a_secret"
  - "cp config/database.yml.example config/database.yml"
  - "bundle exec rake db:create"
  - "bundle exec rake db:schema:load"
  - "bundle exec rake db:test:prepare"
  - "RAILS_ENV=test bundle exec rake db:fixtures:load"
  - "RAILS_ENV=test bundle exec rake ts:index ts:start"
script: "bundle exec rake $RAKE_TASK"
after_script:
  - "cat tmp/*.test*.log" # printing logs from the failed integration tests
notifications:
  email: false

