language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
matrix:
  - fast_finish: true
  - allow_failures:
    - rvm: 2.0.0
    - rvm: 2.1.1
before_install:
  - "bundle --version"
  - sudo apt-get update
  - sudo apt-get install -y graphicsmagick
  - sudo apt-get install -y libreoffice-common
  - sudo apt-get install -y sphinxsearch
  - sudo apt-get install -y inkscape
before_script:
  - "bundle exec rake create_a_secret"
  - "cp config/database.yml.example config/database.yml"
  - "bundle exec rake db:create"
  - "bundle exec rake db:schema:load"
  - "bundle exec rake db:test:prepare"
  - "bundle exec rake RAILS_ENV=test db:fixtures:load"
  - "bundle exec rake RAILS_ENV=test ts:index ts:start"
after_script:
  - "cat tmp/*.test*.log" # printing logs from the failed integration tests
notifications:
  email: false

