<%
  # use a database with the same name as the branch, if the branch is not master:
  db_name = 'core'
  branch = `git branch`.split("\n").grep(/^\*/).first.sub('*','').strip
  if branch != 'master'
    db_name = branch
  end
%>

development:
  encoding: utf8
  adapter: mysql
  database: <%=db_name%>_development
  username: root
  password: 
  host: localhost

test:
  encoding: utf8
  adapter: mysql
  database: <%=db_name%>_test
  username: root
  password: 
  host: localhost

production:
  encoding: utf8
  adapter: mysql
  database: <%=db_name%>_development
  username: root
  password: 
  host: localhost

cucumber:
  encoding: utf8
  adapter: mysql
  database: <%=db_name%>_test
  username: root
  password: 
  host: localhost

culerity_development:
  encoding: utf8
  adapter: mysql
  database: <%=db_name%>_test
  username: root
  password: 
  host: localhost

