# options -------------------------------------------
# searchd log file:: log/searchd.log
# query log file::   log/searchd.query.log
# pid file::         log/searchd.#{environment}.pid
# searchd files::    db/sphinx/#{environment}/
# allow star::       false

common: &common
  indexed_models:
    - PageTerms

development:
  <<: *common
  configuration_file: config/sphinx/development.conf
  mysql41: 3312
  address: localhost
  morphology: stem_en

test:
  <<: *common
  configuration_file: config/sphinx/test.conf
  mysql41: 3313
  address: localhost
  morphology: stem_en

production:
  <<: *common
  configuration_file: config/sphinx/production.conf
  mysql41: 3312
  address: localhost
  morphology: stem_en
  quiet_deltas: true
  bin_path: '/usr/bin'

