#
# This is the main global crabgrass configuration.
#
# Most of the time, no other configuration should be required other than the
# options in this file. Unusual options might be configured elsewhere.
#
# For true/false and numeric values, you must not enclose the value in quotes.
#
# See doc/CONFIGURATION for more details.
#

#
# development tips:
#
#  * to work with super_admin, enable super_admin mod and site 'site1'.
#

title: "Crabgrass Development"

enabled_mods:
  - view_examples
  #- super_admin
  #- moderation
  #- translator

email:
  delivery_method: :sendmail

translation_group: rainbow

text_editor: greencloth_only

#use_full_geonames_data: true

available_page_types:
  - AssetPage
  - DiscussionPage
  - WikiPage
  - EventPage

theme: blueberry

# pagination_size: 3

remote_processing: "http://localhost:3002"

enabled_languages:
  - en
  - es
  - pt
  - ar
  - de

committees: false
councils: false
networks: false

##
## SITES
##

sites:

# bound to localhost:
#  - name: site1
#    theme: blueberry
#    admin_group: rainbow
#    moderation_group: rainbow

# bound to test.host
#  - name: site2
#    admin_group: superadmins

