#
# This is the main global crabgrass configuration.
#
# Most of the time, no other configuration should be required other than the
# options in this file. Unusual options might be configured elsewhere.
#
# For true/false and numeric values, you must not enclose the value in quotes.
#
# See doc/CONFIGURATION for more details.
#

title: "Crabgrass Development"

enabled_mods:
  - view_examples
  - mini_wiki
  #- translator

email:
  delivery_method: :sendmail

translation_group: rainbow

text_editor: greencloth_only

#use_full_geonames_data: true

available_page_types:
  - AssetPage
  - DiscussionPage
  - WikiPage
#  - EventPage #removing for mvs https://labs.riseup.net/code/issues/3349
  - RateManyPage
  - TaskListPage
  - RankedVotePage
  - SurveyPage # we will make available here, but set in its init file that new surveys cannot be added.

theme: blueberry

# pagination_size: 3

remote_processing: "http://localhost:3002"

enabled_languages: ['en', 'es', 'pt', 'ar', 'de', 'fr']

committees: true
councils: true
networks: true

### TRANSLATIONS: 

transifex_user: 'riseuplabs'
transifex_password: 'SET_ME'

##
## SITES
##

sites:

# bound to localhost:
#  - name: site1
#    theme: blueberry
#    admin_group: rainbow
#    moderation_group: rainbow

# bound to test.host
#  - name: site2
#    admin_group: superadmins

default_group_permissions:
  members: !ruby/sym all
  public:
    - view
    - request_membership

default_user_permissions:
  friends:
    - view
    - pester
    - see_groups
    - see_contacts
  peers:
    - pester
    - request_contact
  public: []
