#
# This is the main global crabgrass configuration.
#
# Most of the time, no other configuration should be required other than the
# options in this file. Unusual options might be configured elsewhere.
#
# For true/false and numeric values, you must not enclose the value in quotes.
#
# See doc/CONFIGURATION for more details.
#

title: "Crabgrass Production"

#
# LANGUAGE
#

default_language: en
enabled_languages: ['en', 'es', 'pt', 'ar', 'de', 'fr']

#
# EMAIL
#

# e.g. sendmail
email:
  delivery_method: :sendmail

# e.g. smtp
#email:
#  delivery_method: :smtp
#  smtp_settings:
#    domain: localhost
#    address: smtp.example.com
#    port: 587
#    authentication: :plain
#    user_name: xxxxxx@example.com
#    password: xxxxxxx

email_sender: "robot@$current_host"

#
# PAGES
#

available_page_types:

#
# GROUPS
#

committees: true
councils: true
networks: true

#
# APPEARANCE
#

# pagination_size: 30
# theme: default

#
# SECURITY
#

enforce_ssl: false
show_exceptions: false
tracking: true

#
# MISC
#

text_editor: greencloth_only
remote_processing: "http://localhost:3002"

#
# MODES
#

enabled_mods:

#
# SITES
#

sites:

# bound to localhost:
#  - name: site1
#    theme: blueberry
#    admin_group: rainbow
#    moderation_group: rainbow

# bound to test.host
#  - name: site2
#    admin_group: superadmins

